db.url=jdbc:postgresql://localhost:5432/tour_operator
db.user=postgres
db.password=0807
weather.api.key=9ace7859d603ea7053322716e5f84ada

# Demo-credentials (???????????????? ? LoginController)
# ??? ???????: ????????? ?? ????????? ??????, ? ??? BCrypt ? ??????? users
demo.admin.email=admin@ayvo.ua
demo.admin.password=admin123

# ?? SMTP (??????? ?????????? ?????? ????? JavaMail) ??????????????????????????
# ??? Gmail: ????????? «App password» (2FA ? App passwords) ? ??????? ????.
# ??? Outlook/Office365: ???????? ???? ? ???? ??????????.
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls=true
# ??????-??????????
mail.from=noreply@ayvo.ua
mail.username=tetyanabetsanichh@gmail.com
mail.password=vmlt rnoy kqqx tpxz
mail.dry.run=false

liqpay.public.key=sandbox_i15291823284
liqpay.private.key=sandbox_LuMAtqM4X3vtFSEasrIuuMiv8gh35HZPHS5o6sHP
liqpay.sandbox=true