-- V4: додаємо поля "що включено" до таблиці tours
ALTER TABLE tours ADD COLUMN IF NOT EXISTS meal_type    TEXT    DEFAULT NULL;
ALTER TABLE tours ADD COLUMN IF NOT EXISTS has_flight   BOOLEAN DEFAULT FALSE;
ALTER TABLE tours ADD COLUMN IF NOT EXISTS has_transfer BOOLEAN DEFAULT FALSE;
ALTER TABLE tours ADD COLUMN IF NOT EXISTS has_insurance BOOLEAN DEFAULT FALSE;
ALTER TABLE tours ADD COLUMN IF NOT EXISTS has_guide    BOOLEAN DEFAULT FALSE;
